import { Profile, Service, ServiceOrder, SupportTicket, ChatMessage } from '@/types/database';

export const MOCK_PROFILES: Profile[] = [
  {
    id: 'p-adm-01',
    full_type: 'admin',
    full_name: 'Elena Vance (Admin)',
    email: 'elena.vance@cleanops.com',
    phone: '+1 (555) 234-5678',
    avatar_url: 'https://picsum.photos/seed/elena/100/100',
    company_name: 'CleanOps HQ',
    created_at: '2026-01-10T08:00:00Z',
  },
  {
    id: 'p-ops-01',
    full_type: 'operational',
    full_name: 'Marcus Sterling (Lead Technician)',
    email: 'marcus.s@cleanops.com',
    phone: '+1 (555) 876-5432',
    avatar_url: 'https://picsum.photos/seed/marcus/100/100',
    company_name: 'CleanOps Field Squad A',
    created_at: '2026-01-15T09:30:00Z',
  },
  {
    id: 'p-ops-02',
    full_type: 'operational',
    full_name: 'Sofia Rodriguez (Specialist)',
    email: 'sofia.r@cleanops.com',
    phone: '+1 (555) 987-6543',
    avatar_url: 'https://picsum.photos/seed/sofia/100/100',
    company_name: 'CleanOps Field Squad B',
    created_at: '2026-02-01T10:00:00Z',
  },
  {
    id: 'p-cli-01',
    full_type: 'client',
    full_name: 'Apex Horizon Tech Offices',
    email: 'facilities@apexhorizon.io',
    phone: '+1 (555) 432-1098',
    avatar_url: 'https://picsum.photos/seed/apex/100/100',
    company_name: 'Apex Horizon Inc.',
    created_at: '2026-02-10T14:20:00Z',
  },
  {
    id: 'p-cli-02',
    full_type: 'client',
    full_name: 'Dr. Arthur Pendelton',
    email: 'arthur.p@residence.net',
    phone: '+1 (555) 345-6789',
    avatar_url: 'https://picsum.photos/seed/arthur/100/100',
    company_name: 'Pendelton Estate',
    created_at: '2026-02-18T11:15:00Z',
  },
  {
    id: 'p-cli-03',
    full_type: 'client',
    full_name: 'Lumina Grand Hotel & Suites',
    email: 'management@luminagrand.com',
    phone: '+1 (555) 654-3210',
    avatar_url: 'https://picsum.photos/seed/lumina/100/100',
    company_name: 'Lumina Hospitality Group',
    created_at: '2026-03-01T09:00:00Z',
  }
];

export const MOCK_SERVICES: Service[] = [
  {
    id: 'srv-001',
    title: 'Commercial Office Deep Sanitization',
    description: 'Complete antimicrobial fogging, high-touch point disinfection, HVAC filtration dusting, and corporate floor care.',
    base_price: 480.00,
    category: 'Commercial',
    duration_minutes: 240,
    is_active: true,
    features: ['Hospital-grade disinfectant', 'HEPA air scrubbers', 'Digital compliance certificate'],
    created_at: '2026-01-12T10:00:00Z',
  },
  {
    id: 'srv-002',
    title: 'Luxury Residential Deep Clean',
    description: 'Detailed multi-room cleaning including inside oven/fridge, baseboards, window tracks, and steam sanitized bathrooms.',
    base_price: 290.00,
    category: 'Residential',
    duration_minutes: 180,
    is_active: true,
    features: ['Eco-friendly certified solutions', 'Microfiber dust capture', 'Custom room checklist'],
    created_at: '2026-01-15T11:00:00Z',
  },
  {
    id: 'srv-003',
    title: 'Post-Construction Rough & Final Polish',
    description: 'Removal of drywall dust, adhesive stickers, grout haze, floor scrubbing, and turnkey move-in readiness.',
    base_price: 650.00,
    category: 'Post-Construction',
    duration_minutes: 360,
    is_active: true,
    features: ['Industrial extraction vacuum', 'Sticker and paint scraping', 'Final inspection guarantee'],
    created_at: '2026-01-20T08:30:00Z',
  },
  {
    id: 'srv-004',
    title: 'Move-In / Move-Out Turnkey Clean',
    description: 'Guaranteed lease security deposit return clean for tenants, landlords, and property managers.',
    base_price: 340.00,
    category: 'Move-In/Move-Out',
    duration_minutes: 210,
    is_active: true,
    features: ['Appliance deep degrease', 'Inside cabinets and drawers', 'Carpet edge detail'],
    created_at: '2026-02-05T14:00:00Z',
  },
  {
    id: 'srv-005',
    title: 'Industrial Carpet & Upholstery Extraction',
    description: 'Hot water soil extraction with anti-allergen treatment and rapid drying fan deployment.',
    base_price: 220.00,
    category: 'Carpet & Upholstery',
    duration_minutes: 120,
    is_active: true,
    features: ['Steam extraction 200°F', 'Odor neutralizer', 'Fabric fiber guard'],
    created_at: '2026-02-14T16:00:00Z',
  },
  {
    id: 'srv-006',
    title: 'Ultra-Clean Bio-Disinfection',
    description: 'Certified pathogen decontamination protocol for medical clinics, gyms, and daycare facilities.',
    base_price: 520.00,
    category: 'Disinfection & Sanitization',
    duration_minutes: 180,
    is_active: false,
    features: ['EPA List N virucidal', 'ATP bioluminescence test swab', 'Full PPE operator squad'],
    created_at: '2026-02-20T09:15:00Z',
  }
];

export const MOCK_SERVICE_ORDERS: ServiceOrder[] = [
  {
    id: 'ord-101',
    client_id: 'p-cli-01',
    operational_id: 'p-ops-01',
    service_id: 'srv-001',
    status: 'in_progress',
    scheduled_date: '2026-08-22T14:00:00Z',
    total_price: 480.00,
    address: '742 Evergreen Plaza, Suite 400, Financial District',
    unit_or_suite: 'Floor 4 - Main Server & Open Desks',
    notes: 'Access via rear loading bay with freight elevator. Keycard at security desk.',
    client_signature_url: 'https://picsum.photos/seed/sig1/300/120',
    inspection_photos: [
      'https://picsum.photos/seed/cleanphoto1/600/400',
      'https://picsum.photos/seed/cleanphoto2/600/400',
    ],
    checklist: [
      { id: 'chk-1', task: 'HVAC return intake vents dusted', completed: true, completed_by: 'Marcus S.', timestamp: '14:20' },
      { id: 'chk-2', task: 'Sanitize 42 ergonomic workstations', completed: true, completed_by: 'Marcus S.', timestamp: '15:05' },
      { id: 'chk-3', task: 'Kitchen breakroom high-temp degreasing', completed: false },
      { id: 'chk-4', task: 'Floor electrostatic buff & polish', completed: false },
    ],
    created_at: '2026-08-20T10:15:00Z',
    client: MOCK_PROFILES[3],
    operational: MOCK_PROFILES[1],
    service: MOCK_SERVICES[0],
  },
  {
    id: 'ord-102',
    client_id: 'p-cli-02',
    operational_id: 'p-ops-02',
    service_id: 'srv-002',
    status: 'assigned',
    scheduled_date: '2026-08-23T09:00:00Z',
    total_price: 290.00,
    address: '1428 Elmwood Heights Blvd',
    unit_or_suite: 'Private Villa',
    notes: 'Please pay special attention to master marble bathroom and hardwood polish.',
    client_signature_url: null,
    inspection_photos: [],
    checklist: [
      { id: 'chk-10', task: 'Marble surfaces pH-neutral polished', completed: false },
      { id: 'chk-11', task: 'Kitchen double oven steamed', completed: false },
      { id: 'chk-12', task: 'French windows lint-free polished', completed: false },
      { id: 'chk-13', task: 'Balcony glass balustrades buffed', completed: false },
    ],
    created_at: '2026-08-21T08:00:00Z',
    client: MOCK_PROFILES[4],
    operational: MOCK_PROFILES[2],
    service: MOCK_SERVICES[1],
  },
  {
    id: 'ord-103',
    client_id: 'p-cli-03',
    operational_id: null,
    service_id: 'srv-003',
    status: 'pending',
    scheduled_date: '2026-08-24T08:00:00Z',
    total_price: 650.00,
    address: '89 Waterfront Esplanade',
    unit_or_suite: 'Grand Penthouse B',
    notes: 'Post-renovation cleanup after new Italian porcelain tile installation.',
    client_signature_url: null,
    inspection_photos: [],
    checklist: [
      { id: 'chk-20', task: 'Grout haze removal and dry vacuum', completed: false },
      { id: 'chk-21', task: 'Paint splatter extraction from window sills', completed: false },
      { id: 'chk-22', task: 'Full HVAC register dust extraction', completed: false },
    ],
    created_at: '2026-08-22T09:40:00Z',
    client: MOCK_PROFILES[5],
    operational: null,
    service: MOCK_SERVICES[2],
  },
  {
    id: 'ord-104',
    client_id: 'p-cli-01',
    operational_id: 'p-ops-01',
    service_id: 'srv-005',
    status: 'completed',
    scheduled_date: '2026-08-19T13:00:00Z',
    total_price: 220.00,
    address: '742 Evergreen Plaza, Suite 400',
    unit_or_suite: 'Conference Room Alpha & Beta',
    notes: 'Coffee stain removal on executive meeting room wool rug.',
    client_signature_url: 'https://picsum.photos/seed/sig2/300/120',
    inspection_photos: [
      'https://picsum.photos/seed/carpet1/600/400',
      'https://picsum.photos/seed/carpet2/600/400',
    ],
    checklist: [
      { id: 'chk-30', task: 'Pre-spray spot treatment applied', completed: true, completed_by: 'Marcus S.', timestamp: '13:15' },
      { id: 'chk-31', task: '200°F Deep steam extraction performed', completed: true, completed_by: 'Marcus S.', timestamp: '14:00' },
      { id: 'chk-32', task: 'Commercial turbo dryers placed', completed: true, completed_by: 'Marcus S.', timestamp: '14:30' },
      { id: 'chk-33', task: 'Client walk-through inspection passed', completed: true, completed_by: 'Marcus S.', timestamp: '15:10' },
    ],
    created_at: '2026-08-18T11:00:00Z',
    client: MOCK_PROFILES[3],
    operational: MOCK_PROFILES[1],
    service: MOCK_SERVICES[4],
  }
];

export const MOCK_TICKETS: SupportTicket[] = [
  {
    id: 'tkt-501',
    client_id: 'p-cli-01',
    assigned_to: 'p-adm-01',
    service_order_id: 'ord-101',
    subject: 'Requesting extra disinfectant in server room cooling corridor',
    category: 'Special Instruction',
    status: 'in_progress',
    priority: 'high',
    created_at: '2026-08-22T10:30:00Z',
    client: MOCK_PROFILES[3],
    assigned_staff: MOCK_PROFILES[0],
    service_order: MOCK_SERVICE_ORDERS[0],
    unread_count: 1,
  },
  {
    id: 'tkt-502',
    client_id: 'p-cli-03',
    assigned_to: 'p-adm-01',
    service_order_id: 'ord-103',
    subject: 'Ombudsman: Inquire about early dispatch time at 7:30 AM',
    category: 'Schedule Adjustment',
    status: 'open',
    priority: 'urgent',
    created_at: '2026-08-22T11:10:00Z',
    client: MOCK_PROFILES[5],
    assigned_staff: MOCK_PROFILES[0],
    service_order: MOCK_SERVICE_ORDERS[2],
    unread_count: 2,
  },
  {
    id: 'tkt-503',
    client_id: 'p-cli-02',
    assigned_to: 'p-adm-01',
    service_order_id: null,
    subject: 'Billing inquiry: Request consolidated monthly invoice copy',
    category: 'Billing & Invoicing',
    status: 'resolved',
    priority: 'low',
    resolution_notes: 'Sent consolidated PDF tax invoice to arthur.p@residence.net with stamp.',
    created_at: '2026-08-15T15:20:00Z',
    client: MOCK_PROFILES[4],
    assigned_staff: MOCK_PROFILES[0],
    service_order: null,
    unread_count: 0,
  }
];

export const MOCK_CHAT_MESSAGES: Record<string, ChatMessage[]> = {
  'tkt-501': [
    {
      id: 'msg-01',
      ticket_id: 'tkt-501',
      sender_id: 'p-cli-01',
      message: 'Hello SAC team! During today\'s commercial service order, could the team make sure not to spray liquid mist directly over rack 3 in the server room? Please use antistatic dry wipes there.',
      created_at: '2026-08-22T10:30:00Z',
      sender: MOCK_PROFILES[3],
    },
    {
      id: 'msg-02',
      ticket_id: 'tkt-501',
      sender_id: 'p-adm-01',
      message: 'Hi Apex Facilities team! Thank you for the note. I am notifying Lead Technician Marcus Sterling right away to follow ESD-safe dry wipe protocols for rack 3.',
      created_at: '2026-08-22T10:35:00Z',
      sender: MOCK_PROFILES[0],
    },
    {
      id: 'msg-03',
      ticket_id: 'tkt-501',
      sender_id: 'p-ops-01',
      message: 'Acknowledged from the site. We are utilizing specialized class-100 antistatic microfiber wipes on rack 3. All safe!',
      created_at: '2026-08-22T10:45:00Z',
      sender: MOCK_PROFILES[1],
    },
    {
      id: 'msg-04',
      ticket_id: 'tkt-501',
      sender_id: 'p-adm-01',
      message: 'INTERNAL NOTE: Field squad confirmed protocol adherence. Compliance logged for audit report.',
      is_internal_note: true,
      created_at: '2026-08-22T10:47:00Z',
      sender: MOCK_PROFILES[0],
    }
  ],
  'tkt-502': [
    {
      id: 'msg-10',
      ticket_id: 'tkt-502',
      sender_id: 'p-cli-03',
      message: 'Good morning. We have early hotel VIP arrivals on the 24th. Can our post-construction clean crew arrive at 7:30 AM instead of 8:00 AM?',
      created_at: '2026-08-22T11:10:00Z',
      sender: MOCK_PROFILES[5],
    }
  ],
  'tkt-503': [
    {
      id: 'msg-20',
      ticket_id: 'tkt-503',
      sender_id: 'p-cli-02',
      message: 'Could you please send over the official PDF receipt for my recent clean?',
      created_at: '2026-08-15T15:20:00Z',
      sender: MOCK_PROFILES[4],
    },
    {
      id: 'msg-21',
      ticket_id: 'tkt-503',
      sender_id: 'p-adm-01',
      message: 'Certainly Dr. Pendelton! The official receipt has been emailed and attached to your records.',
      created_at: '2026-08-15T16:00:00Z',
      sender: MOCK_PROFILES[0],
    }
  ]
};
